---
language: python
services: docker

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint testinfra flake8 docker

script:
  # Run tests.
  - molecule --version
  - ansible --version
  - molecule test
