---
- hosts: all
  become: yes
  tasks:

    - name: install sidecar
      yum:
        name: https://github.com/Graylog2/collector-sidecar/releases/download/1.0.2/graylog-sidecar-1.0.2-1.x86_64.rpm
        state: present
    - name: install filebeat
      yum:
        name: https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-6.8.3-x86_64.rpm
        state: present
    - name: set graylog server url
      lineinfile:
        path: /etc/graylog/sidecar/sidecar.yml
        regexp: "^server_url"
        insertafter: '^#server_url'
        line: 'server_url: "http://192.168.56.100:80/api/"'
    - name: set graylog server api token
      lineinfile:
        path: /etc/graylog/sidecar/sidecar.yml
        regexp: "^server_api_token"
        line: 'server_api_token: "1956ajl3g8aqpmr23rt6idoes4uha078jm7garv9steg8mgo9ocu"'
    - name: install sidecar service
      command: /usr/bin/graylog-sidecar -service install
      args:
        creates: /etc/systemd/system/graylog-sidecar.service
    - name: start sidecar service
      service:
        name: graylog-sidecar
        state: started

